// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: bandcampserver.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BandcampServerServiceClient is the client API for BandcampServerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BandcampServerServiceClient interface {
	SetToken(ctx context.Context, in *SetTokenRequest, opts ...grpc.CallOption) (*SetTokenResponse, error)
	AddMapping(ctx context.Context, in *AddMappingRequest, opts ...grpc.CallOption) (*AddMappingResponse, error)
	Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetResponse, error)
	Lookup(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*LookupResponse, error)
}

type bandcampServerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBandcampServerServiceClient(cc grpc.ClientConnInterface) BandcampServerServiceClient {
	return &bandcampServerServiceClient{cc}
}

func (c *bandcampServerServiceClient) SetToken(ctx context.Context, in *SetTokenRequest, opts ...grpc.CallOption) (*SetTokenResponse, error) {
	out := new(SetTokenResponse)
	err := c.cc.Invoke(ctx, "/bandcampserver.BandcampServerService/SetToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bandcampServerServiceClient) AddMapping(ctx context.Context, in *AddMappingRequest, opts ...grpc.CallOption) (*AddMappingResponse, error) {
	out := new(AddMappingResponse)
	err := c.cc.Invoke(ctx, "/bandcampserver.BandcampServerService/AddMapping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bandcampServerServiceClient) Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetResponse, error) {
	out := new(ResetResponse)
	err := c.cc.Invoke(ctx, "/bandcampserver.BandcampServerService/Reset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bandcampServerServiceClient) Lookup(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*LookupResponse, error) {
	out := new(LookupResponse)
	err := c.cc.Invoke(ctx, "/bandcampserver.BandcampServerService/Lookup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BandcampServerServiceServer is the server API for BandcampServerService service.
// All implementations should embed UnimplementedBandcampServerServiceServer
// for forward compatibility
type BandcampServerServiceServer interface {
	SetToken(context.Context, *SetTokenRequest) (*SetTokenResponse, error)
	AddMapping(context.Context, *AddMappingRequest) (*AddMappingResponse, error)
	Reset(context.Context, *ResetRequest) (*ResetResponse, error)
	Lookup(context.Context, *LookupRequest) (*LookupResponse, error)
}

// UnimplementedBandcampServerServiceServer should be embedded to have forward compatible implementations.
type UnimplementedBandcampServerServiceServer struct {
}

func (UnimplementedBandcampServerServiceServer) SetToken(context.Context, *SetTokenRequest) (*SetTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetToken not implemented")
}
func (UnimplementedBandcampServerServiceServer) AddMapping(context.Context, *AddMappingRequest) (*AddMappingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMapping not implemented")
}
func (UnimplementedBandcampServerServiceServer) Reset(context.Context, *ResetRequest) (*ResetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reset not implemented")
}
func (UnimplementedBandcampServerServiceServer) Lookup(context.Context, *LookupRequest) (*LookupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lookup not implemented")
}

// UnsafeBandcampServerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BandcampServerServiceServer will
// result in compilation errors.
type UnsafeBandcampServerServiceServer interface {
	mustEmbedUnimplementedBandcampServerServiceServer()
}

func RegisterBandcampServerServiceServer(s grpc.ServiceRegistrar, srv BandcampServerServiceServer) {
	s.RegisterService(&BandcampServerService_ServiceDesc, srv)
}

func _BandcampServerService_SetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BandcampServerServiceServer).SetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bandcampserver.BandcampServerService/SetToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BandcampServerServiceServer).SetToken(ctx, req.(*SetTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BandcampServerService_AddMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BandcampServerServiceServer).AddMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bandcampserver.BandcampServerService/AddMapping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BandcampServerServiceServer).AddMapping(ctx, req.(*AddMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BandcampServerService_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BandcampServerServiceServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bandcampserver.BandcampServerService/Reset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BandcampServerServiceServer).Reset(ctx, req.(*ResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BandcampServerService_Lookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BandcampServerServiceServer).Lookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bandcampserver.BandcampServerService/Lookup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BandcampServerServiceServer).Lookup(ctx, req.(*LookupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BandcampServerService_ServiceDesc is the grpc.ServiceDesc for BandcampServerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BandcampServerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bandcampserver.BandcampServerService",
	HandlerType: (*BandcampServerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetToken",
			Handler:    _BandcampServerService_SetToken_Handler,
		},
		{
			MethodName: "AddMapping",
			Handler:    _BandcampServerService_AddMapping_Handler,
		},
		{
			MethodName: "Reset",
			Handler:    _BandcampServerService_Reset_Handler,
		},
		{
			MethodName: "Lookup",
			Handler:    _BandcampServerService_Lookup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bandcampserver.proto",
}
